test:
  image: python:3.6
  script:
  - pip install -r requirements.txt --upgrade
  - nosetests .
  - mypy .
  - flake8 .
  - python train.py -n 1 -i tests/data/items_for_test.pickle -l -s 48 --type vgg16 -w /tmp/test.hdf5 --test-set-share 0.2 -t
  - rm -f /tmp/test*.hdf5
